name: Move readme

on:
  push:
    branches: [ main ]
    paths:
      - 'addons/Trust/data/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'addons/Trust/data/**'
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PUSH_KEY }}
      
      - name: Move the readme file
        run: ./generate_readme.sh
      
      - name: Commit and push changes
        run: |
          git config user.name "cyrite"
          git config user.email "cyritegamestudios@gmail.com" 
          
          git add -A
          git commit -m "Automatically updating README.md"
          git push
